namespace WebExpress.UI.WebControl
{
    public enum TypeIcon
    {
        None,
        AlignCenter,
        AlignJustify,
        AlignLeft,
        AlignRight,
        AngleDown,
        AngleLeft,
        AngleRight,
        AngleUp,
        ArrowDown,
        ArrowLeft,
        ArrowRight,
        ArrowUp,
        At,
        Bars,
        Bold,
        Bolt,
        Bomb,
        Book,
        Bug,
        Building,
        Calendar,
        CalendarMinus,
        CalendarPlus,
        Car,
        CaretDown,
        CaretLeft,
        CaretRight,
        CaretUp,
        ChartBar,
        City,
        Clock,
        Clone,
        Code,
        Cog,
        Copy,
        Comment,
        CommentAlt,
        Cube,
        Cubes,
        Database,
        Door,
        DoorOpen,
        Download,
        Edit,
        EllipsisHorizontal,
        EllipsisVertical,
        EuroSign,
        ExclamationTriangle,
        Fire,
        Folder,
        FolderOpen,
        Font,
        Forward,
        GraduationCap,
        Hashtag,
        Hdd,
        Home,
        Image,
        Industry,
        Info,
        InfoCircle,
        Key,
        LayerGroup,
        Lightbulb,
        Link,
        Map,
        MapMarker,
        Microchip,
        PaperClip,
        PaperPlane,
        PlayCircle,
        Plug,
        Plus,
        PowerOff,
        Print,
        Road,
        Save,
        ShoppingBag,
        Star,
        StopCircle,
        Stopwatch,
        Sun,
        TachometerAlt,
        ThermometerQuarter,
        Tag,
        Tags,
        Times,
        Trash,
        TrashAlt,
        Truck,
        ThumbsUp,
        Undo,
        Upload,
        Users
    }

    public static class TypeIconExtensions
    {
        /// <summary>
        /// Umwandlung in eine CSS-Klasse
        /// </summary>
        /// <param name="icon">Das Icon, welches umgewandelt werden soll</param>
        /// <returns>Die zum Icon gehörende CSS-KLasse</returns>
        public static string ToClass(this TypeIcon icon)
        {
            return icon switch
            {
                TypeIcon.AlignCenter => "fas fa-align-center",
                TypeIcon.AlignJustify => "fas fa-align-justify",
                TypeIcon.AlignLeft => "fas fa-align-left",
                TypeIcon.AlignRight => "fas fa-align-right",
                TypeIcon.AngleDown => "fas fa-angle-down",
                TypeIcon.AngleLeft => "fas fa-angle-left",
                TypeIcon.AngleRight => "fas fa-angle-right",
                TypeIcon.AngleUp => "fas fa-angle-up",
                TypeIcon.ArrowDown => "fas fa-arrow-down",
                TypeIcon.ArrowLeft => "fas fa-arrow-left",
                TypeIcon.ArrowRight => "fas fa-arrow-right",
                TypeIcon.ArrowUp => "fas fa-arrow-up",
                TypeIcon.At => "fas fa-at",
                TypeIcon.Bars => "fas fa-bars",
                TypeIcon.Bold => "fas fa-bold",
                TypeIcon.Bolt => "fas fa-bolt",
                TypeIcon.Bomb => "fas fa-bomb",
                TypeIcon.Book => "fas fa-book",
                TypeIcon.Bug => "fas fa-bug",
                TypeIcon.Building => "fas fa-building",
                TypeIcon.Calendar => "fas fa-calendar",
                TypeIcon.CalendarMinus => "fas fa-calendar-minus",
                TypeIcon.CalendarPlus => "fas fa-calendar-plus",
                TypeIcon.Car => "fas fa-car",
                TypeIcon.CaretDown => "fas fa-caret-down",
                TypeIcon.CaretLeft => "fas fa-caret-left",
                TypeIcon.CaretRight => "fas fa-caret-right",
                TypeIcon.CaretUp => "fas fa-caret-up",
                TypeIcon.ChartBar => "fas fa-chart-bar",
                TypeIcon.City => "fas fa-city",
                TypeIcon.Clock => "fas fa-clock",
                TypeIcon.Clone => "fas fa-clone",
                TypeIcon.Code => "fas fa-code",
                TypeIcon.Cog => "fas fa-cog",
                TypeIcon.Copy => "fas fa-copy",
                TypeIcon.Comment => "fas fa-comment",
                TypeIcon.CommentAlt => "fas fa-comment-alt",
                TypeIcon.Cube => "fas fa-cube",
                TypeIcon.Cubes => "fas fa-cubes",
                TypeIcon.Database => "fas fa-database",
                TypeIcon.Door => "fas fa-door-closed",
                TypeIcon.DoorOpen => "fas fa-door-open",
                TypeIcon.Download => "fas fa-upload",
                TypeIcon.Edit => "fas fa-edit",
                TypeIcon.EllipsisHorizontal => "fas fa-ellipsis-h",
                TypeIcon.EllipsisVertical => "fas fa-ellipsis-v",
                TypeIcon.EuroSign => "fas fa-euro-sign",
                TypeIcon.ExclamationTriangle => "fas fa-exclamation-triangle",
                TypeIcon.Fire => "fas fa-fire",
                TypeIcon.Folder => "fas fa-folder",
                TypeIcon.FolderOpen => "fas fa-folder-open",
                TypeIcon.Font => "fas fa-font",
                TypeIcon.Forward => "fas fa-forward",
                TypeIcon.GraduationCap => "fas fa-graduation-cap",
                TypeIcon.Hashtag => "fas fa-hashtag",
                TypeIcon.Hdd => "fas fa-hdd",
                TypeIcon.Home => "fas fa-home",
                TypeIcon.Image => "fas fa-image",
                TypeIcon.Industry => "fas fa-industry",
                TypeIcon.Info => "fas fa-info",
                TypeIcon.InfoCircle => "fas fa-info-circle",
                TypeIcon.Key => "fas fa-key",
                TypeIcon.LayerGroup => "fas fa-layer-group",
                TypeIcon.Lightbulb => "fas fa-lightbulb",
                TypeIcon.Link => "fas fa-link",
                TypeIcon.Map => "fas fa-map",
                TypeIcon.MapMarker => "fas fa-map-marker",
                TypeIcon.Microchip => "fas fa-microchip",
                TypeIcon.PaperClip => "fas fa-paperclip",
                TypeIcon.PaperPlane => "fas fa-paper-plane",
                TypeIcon.PlayCircle => "fas fa-play-circle",
                TypeIcon.Plug => "fas fa-plug",
                TypeIcon.Plus => "fas fa-plus",
                TypeIcon.PowerOff => "fas fa-power-off",
                TypeIcon.Print => "fas fa-print",
                TypeIcon.Road => "fas fa-road",
                TypeIcon.Save => "fas fa-save",
                TypeIcon.ShoppingBag => "fas fa-shopping-bag",
                TypeIcon.Star => "fas fa-star",
                TypeIcon.StopCircle => "fas fa-stop-circle",
                TypeIcon.Stopwatch => "fas fa-stopwatch",
                TypeIcon.Sun => "fas fa-sun",
                TypeIcon.TachometerAlt => "fas fa-tachometer-alt",
                TypeIcon.Tag => "fas fa-tag",
                TypeIcon.Tags => "fas fa-tags",
                TypeIcon.ThermometerQuarter => "fas fa-thermometer-quarter",
                TypeIcon.Times => "fas fa-times",
                TypeIcon.Trash => "fas fa-trash",
                TypeIcon.TrashAlt => "fas fa-trash-alt",
                TypeIcon.Truck => "fas fa-truck",
                TypeIcon.ThumbsUp => "fas fa-thumbs-up",
                TypeIcon.Undo => "fas fa-undo",
                TypeIcon.Upload => "fas fa-download",
                TypeIcon.Users => "fas fa-users",
                _ => string.Empty,
            };
        }
    }
}
